#docker-compose.yaml
services:
  ocr-service:
    build:
      context: .
      dockerfile: ocr-service/Dockerfile
    ports:
      - "9000:9000"
    environment:
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
    volumes:
      - data:/data

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - ocr-service
    environment:
      - OCR_SERVICE_URL=http://ocr-service:9000/process

  fe:
    build:
      context: .
      dockerfile: fe/Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - api

volumes:
  data:
