# docker-compose.yml
#version: '3.9'

services:
  ocr-service:
    build:
      context: .
      dockerfile: ocr-service/Dockerfile
    env_file:
      - .env
    ports:
      - "9000:9000"
    volumes:
      - data:/data

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    env_file:
      - .env
    depends_on:
      - ocr-service
    environment:
      - OCR_SERVICE_URL=http://ocr-service:9000/ocr
    ports:
      - "8000:8000"

  fe:
    build:
      context: .
      dockerfile: fe/Dockerfile
    env_file:
      - .env
    depends_on:
      - api
    ports:
      - "8501:8501"

volumes:
  data:
