services:
  api:
    build:
      context: .                 # gốc repo
      dockerfile: api/Dockerfile
    image: ocr-api:1.0
    container_name: ocr-api
    env_file: .env
    volumes:
      - ./data:/data
    ports:
      - "8000:8000"
    restart: unless-stopped
